export const NAV_LINKS = [
  { href: '/', label: 'Ana Sayfa' },
  { href: '/products', label: 'Kategoriler' },
  { href: '/products', label: 'Ürünler' },
  { href: '/stores', label: 'Şubelerimiz' },
  { href: '/contact', label: 'İletişim' },
];

export const CATEGORIES = [
  {
    id: 1,
    title: 'Ofis Mobilyaları',
    subtitle: 'Masa, koltuk, dolap çözümleri',
    image: 'https://images.unsplash.com/photo-1497215842964-222b430dc094?q=80&w=800',
    count: '150+ Ürün',
    delivery: 'Hızlı teslimat',
    delay: '100ms',
  },
  {
    id: 2,
    title: 'Yönetici Mobilyaları',
    subtitle: 'Yönetici odası komple çözümler',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=800',
    count: '80+ Ürün',
    delivery: 'Özel üretim seçenekleri',
    delay: '200ms',
  },
  {
    id: 3,
    title: 'Toplantı & Ortak Alan',
    subtitle: 'Toplantı masaları ve oturma alanları',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=800',
    count: '120+ Ürün',
    delivery: 'Kurulum dahil',
    delay: '300ms',
  },
  {
    id: 4,
    title: 'Depolama',
    subtitle: 'Arşiv ve depolama sistemleri',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=800',
    count: '90+ Ürün',
    delivery: 'Ölçüye göre üretim',
    delay: '400ms',
  },
  {
    id: 5,
    title: 'Proje / Özel Üretim',
    subtitle: 'Kurumsal projeler için özel çözümler',
    image: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?q=80&w=800',
    count: 'Özel Çözümler',
    delivery: 'Proje bazlı',
    delay: '500ms',
  },
];

export const PRODUCTS = [
  {
    id: 1,
    name: 'Ergonomic Çalışma Masası',
    price: '12.990₺',
    originalPrice: '15.990₺',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=800',
    badges: ['Stokta'],
    features: ['Ölçüye göre üretim', 'Ücretsiz teslimat'],
    delay: '100ms',
    inStock: true,
    category: 'Ofis Mobilyaları',
    description: 'Modern ofisler için tasarlanmış, ergonomi ve şıklığı birleştiren üst düzey çalışma masası. Uzun çalışma saatleri için optimize edilmiş yüksek kaliteli malzemelerden üretilmiştir.',
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1600',
      'https://images.unsplash.com/photo-1497215842964-222b430dc094?q=80&w=1600',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=1600',
      'https://images.unsplash.com/photo-1497366754035-f200968a6e72?q=80&w=1600',
    ],
    specs: [
      { label: 'Masa Ölçüleri', value: '180 x 80 x 75 cm' },
      { label: 'Malzeme', value: 'Doğal Ahşap Kaplama, Metal Ayak' },
      { label: 'Renk Seçenekleri', value: 'Ceviz, Meşe, Antrasit' },
      { label: 'Kullanım Alanı', value: 'Ofis, Çalışma Odası' },
      { label: 'Garanti', value: '2 Yıl Kurumsal Garanti' },
    ],
    deliveryTime: '3-5 İş Günü',
    detailedFeatures: [
      'Ücretsiz Teslimat ve Kurulum',
      'Özel Ölçü Seçeneği',
      'Kablo Yönetim Sistemi',
      'Leke Tutmaz Yüzey',
      'Ergonomik Tasarım',
    ],
  },
  {
    id: 2,
    name: 'Yönetici Koltuk Seti',
    price: '24.990₺',
    originalPrice: '29.990₺',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=800',
    badges: ['Stokta'],
    features: ['Kurulum dahil', '2 yıl garanti'],
    delay: '200ms',
    inStock: true,
    category: 'Yönetici Mobilyaları',
    description: 'Yönetici odaları için özel olarak tasarlanmış lüks koltuk seti. Premium deri kaplama ve gelişmiş ergonomi özellikleri ile uzun süreli oturma konforu sağlar.',
    images: [
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=1600',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1600',
      'https://images.unsplash.com/photo-1497215842964-222b430dc094?q=80&w=1600',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=1600',
    ],
    specs: [
      { label: 'Koltuk Ölçüleri', value: '75 x 75 x 120 cm' },
      { label: 'Malzeme', value: 'Premium Deri, Metal Çerçeve' },
      { label: 'Renk Seçenekleri', value: 'Siyah, Kahverengi, Gri' },
      { label: 'Kullanım Alanı', value: 'Yönetici Odası, Toplantı Odası' },
      { label: 'Garanti', value: '2 Yıl Kurumsal Garanti' },
    ],
    deliveryTime: '5-7 İş Günü',
    detailedFeatures: [
      'Ücretsiz Teslimat ve Kurulum',
      'Ayarlanabilir Yükseklik',
      'Lumbar Destek Sistemi',
      '360° Döner Taban',
      'Premium Deri Kaplama',
    ],
  },
  {
    id: 3,
    name: 'Toplantı Masası Seti',
    price: '18.990₺',
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1497215842964-222b430dc094?q=80&w=800',
    badges: ['Stokta'],
    features: ['Hızlı teslimat', 'Montaj desteği'],
    delay: '300ms',
    inStock: true,
    category: 'Toplantı & Ortak Alan',
    description: 'Kurumsal toplantı odaları için ideal, geniş ve şık toplantı masası seti. Modern tasarımı ve dayanıklı yapısı ile uzun yıllar kullanım sağlar.',
    images: [
      'https://images.unsplash.com/photo-1497215842964-222b430dc094?q=80&w=1600',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1600',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=1600',
      'https://images.unsplash.com/photo-1497366754035-f200968a6e72?q=80&w=1600',
    ],
    specs: [
      { label: 'Masa Ölçüleri', value: '300 x 120 x 75 cm' },
      { label: 'Malzeme', value: 'Laminat Yüzey, Metal Ayak' },
      { label: 'Renk Seçenekleri', value: 'Beyaz, Meşe, Ceviz' },
      { label: 'Kullanım Alanı', value: 'Toplantı Odası, Konferans Salonu' },
      { label: 'Garanti', value: '2 Yıl Kurumsal Garanti' },
    ],
    deliveryTime: '7-10 İş Günü',
    detailedFeatures: [
      'Ücretsiz Teslimat ve Kurulum',
      'Geniş Oturma Kapasitesi',
      'Kablo Yönetim Sistemi',
      'Dayanıklı Yüzey',
      'Modüler Tasarım',
    ],
  },
  // Ofis Mobilyaları - Ek Ürünler
  {
    id: 4,
    name: 'Standart Ofis Koltuk',
    price: '8.990₺',
    originalPrice: '11.990₺',
    image: 'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?q=80&w=800',
    badges: ['Stokta'],
    features: ['Ergonomik tasarım', 'Ayarlanabilir yükseklik'],
    delay: '400ms',
    inStock: true,
    category: 'Ofis Mobilyaları',
    description: 'Günlük ofis kullanımı için ideal, konforlu ve dayanıklı ofis koltuğu. Ergonomik tasarımı ile uzun süreli oturma konforu sağlar.',
    images: [
      'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?q=80&w=1600',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1600',
      'https://images.unsplash.com/photo-1497215842964-222b430dc094?q=80&w=1600',
    ],
    specs: [
      { label: 'Koltuk Ölçüleri', value: '60 x 60 x 110 cm' },
      { label: 'Malzeme', value: 'Mesh Kumaş, Metal Çerçeve' },
      { label: 'Renk Seçenekleri', value: 'Siyah, Gri, Mavi' },
      { label: 'Kullanım Alanı', value: 'Ofis, Çalışma Odası' },
      { label: 'Garanti', value: '2 Yıl Kurumsal Garanti' },
    ],
    deliveryTime: '3-5 İş Günü',
    detailedFeatures: [
      'Ücretsiz Teslimat',
      'Ayarlanabilir Yükseklik',
      'Lumbar Destek',
      '360° Döner Taban',
      'Mesh Kumaş Kaplama',
    ],
  },
  {
    id: 5,
    name: 'Ofis Dolap Seti',
    price: '15.990₺',
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=800',
    badges: ['Stokta'],
    features: ['Geniş depolama', 'Dosya sistemi'],
    delay: '500ms',
    inStock: true,
    category: 'Ofis Mobilyaları',
    description: 'Ofisler için pratik ve geniş depolama alanı sunan dolap seti. Dosya ve evrak organizasyonu için ideal çözüm.',
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=1600',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1600',
      'https://images.unsplash.com/photo-1497215842964-222b430dc094?q=80&w=1600',
    ],
    specs: [
      { label: 'Dolap Ölçüleri', value: '120 x 40 x 180 cm' },
      { label: 'Malzeme', value: 'Laminat, Metal Aksesuar' },
      { label: 'Renk Seçenekleri', value: 'Beyaz, Meşe, Gri' },
      { label: 'Kullanım Alanı', value: 'Ofis, Arşiv Odası' },
      { label: 'Garanti', value: '2 Yıl Kurumsal Garanti' },
    ],
    deliveryTime: '5-7 İş Günü',
    detailedFeatures: [
      'Ücretsiz Teslimat ve Kurulum',
      'Geniş Depolama Alanı',
      'Dosya Sistemi',
      'Kilitli Bölmeler',
      'Modüler Tasarım',
    ],
  },
  {
    id: 6,
    name: 'L Şeklinde Köşe Masa',
    price: '14.990₺',
    originalPrice: '17.990₺',
    image: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?q=80&w=800',
    badges: ['Stokta'],
    features: ['Köşe tasarım', 'Geniş çalışma alanı'],
    delay: '600ms',
    inStock: true,
    category: 'Ofis Mobilyaları',
    description: 'Köşe ofisler için ideal L şeklinde çalışma masası. Geniş çalışma alanı ve modern tasarımı ile dikkat çeker.',
    images: [
      'https://images.unsplash.com/photo-1497366754035-f200968a6e72?q=80&w=1600',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1600',
      'https://images.unsplash.com/photo-1497215842964-222b430dc094?q=80&w=1600',
    ],
    specs: [
      { label: 'Masa Ölçüleri', value: '160 x 120 x 75 cm (L şekli)' },
      { label: 'Malzeme', value: 'Laminat Yüzey, Metal Ayak' },
      { label: 'Renk Seçenekleri', value: 'Beyaz, Meşe, Ceviz' },
      { label: 'Kullanım Alanı', value: 'Ofis, Köşe Çalışma Alanı' },
      { label: 'Garanti', value: '2 Yıl Kurumsal Garanti' },
    ],
    deliveryTime: '5-7 İş Günü',
    detailedFeatures: [
      'Ücretsiz Teslimat ve Kurulum',
      'L Şeklinde Tasarım',
      'Kablo Yönetim Sistemi',
      'Geniş Çalışma Alanı',
      'Dayanıklı Yapı',
    ],
  },
  {
    id: 7,
    name: 'Ofis Sehpa Seti',
    price: '6.990₺',
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=800',
    badges: ['Stokta'],
    features: ['Modern tasarım', 'Bekleme alanı'],
    delay: '700ms',
    inStock: true,
    category: 'Ofis Mobilyaları',
    description: 'Ofis bekleme alanları ve resepsiyon için şık sehpa seti. Modern tasarımı ile ofis atmosferini zenginleştirir.',
    images: [
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=1600',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1600',
      'https://images.unsplash.com/photo-1497215842964-222b430dc094?q=80&w=1600',
    ],
    specs: [
      { label: 'Sehpa Ölçüleri', value: '120 x 60 x 45 cm' },
      { label: 'Malzeme', value: 'Cam Yüzey, Metal Ayak' },
      { label: 'Renk Seçenekleri', value: 'Şeffaf Cam, Siyah Ayak' },
      { label: 'Kullanım Alanı', value: 'Bekleme Alanı, Resepsiyon' },
      { label: 'Garanti', value: '1 Yıl Kurumsal Garanti' },
    ],
    deliveryTime: '3-5 İş Günü',
    detailedFeatures: [
      'Ücretsiz Teslimat',
      'Modern Tasarım',
      'Cam Yüzey',
      'Dayanıklı Metal Ayak',
      'Kolay Temizlik',
    ],
  },
  {
    id: 8,
    name: 'Yönetici Çalışma Masası',
    price: '19.990₺',
    originalPrice: '24.990₺',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=800',
    badges: ['Stokta'],
    features: ['Premium malzeme', 'Geniş çalışma alanı'],
    delay: '800ms',
    inStock: true,
    category: 'Yönetici Mobilyaları',
    description: 'Yönetici odaları için özel tasarlanmış premium çalışma masası. Lüks görünümü ve geniş çalışma alanı ile dikkat çeker.',
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1600',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=1600',
      'https://images.unsplash.com/photo-1497215842964-222b430dc094?q=80&w=1600',
    ],
    specs: [
      { label: 'Masa Ölçüleri', value: '200 x 100 x 75 cm' },
      { label: 'Malzeme', value: 'Doğal Ceviz Kaplama, Metal Ayak' },
      { label: 'Renk Seçenekleri', value: 'Ceviz, Meşe, Antrasit' },
      { label: 'Kullanım Alanı', value: 'Yönetici Odası' },
      { label: 'Garanti', value: '3 Yıl Kurumsal Garanti' },
    ],
    deliveryTime: '7-10 İş Günü',
    detailedFeatures: [
      'Ücretsiz Teslimat ve Kurulum',
      'Premium Malzeme',
      'Geniş Çalışma Alanı',
      'Kablo Yönetim Sistemi',
      'Lüks Tasarım',
    ],
  },
  {
    id: 9,
    name: 'Yönetici Konferans Masası',
    price: '22.990₺',
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1497215842964-222b430dc094?q=80&w=800',
    badges: ['Stokta'],
    features: ['Büyük boy', 'Toplantı odası'],
    delay: '900ms',
    inStock: true,
    category: 'Yönetici Mobilyaları',
    description: 'Yönetici toplantı odaları için özel tasarlanmış büyük konferans masası. Prestijli görünümü ile kurumsal imajı güçlendirir.',
    images: [
      'https://images.unsplash.com/photo-1497215842964-222b430dc094?q=80&w=1600',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1600',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=1600',
    ],
    specs: [
      { label: 'Masa Ölçüleri', value: '350 x 120 x 75 cm' },
      { label: 'Malzeme', value: 'Doğal Ahşap, Metal Çerçeve' },
      { label: 'Renk Seçenekleri', value: 'Ceviz, Meşe, Siyah' },
      { label: 'Kullanım Alanı', value: 'Yönetici Toplantı Odası' },
      { label: 'Garanti', value: '3 Yıl Kurumsal Garanti' },
    ],
    deliveryTime: '10-14 İş Günü',
    detailedFeatures: [
      'Ücretsiz Teslimat ve Kurulum',
      'Büyük Boy Tasarım',
      'Premium Malzeme',
      'Kablo Yönetim Sistemi',
      'Prestijli Görünüm',
    ],
  },
  {
    id: 10,
    name: 'Yönetici Ziyaretçi Koltuk Seti',
    price: '16.990₺',
    originalPrice: '19.990₺',
    image: 'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?q=80&w=800',
    badges: ['Stokta'],
    features: ['2+1 set', 'Premium deri'],
    delay: '1000ms',
    inStock: true,
    category: 'Yönetici Mobilyaları',
    description: 'Yönetici odaları için şık ziyaretçi koltuk seti. Premium deri kaplama ve konforlu tasarımı ile misafirlerinizi etkiler.',
    images: [
      'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?q=80&w=1600',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=1600',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1600',
    ],
    specs: [
      { label: 'Set İçeriği', value: '2 Koltuk + 1 Koltuk' },
      { label: 'Malzeme', value: 'Premium Deri, Ahşap Çerçeve' },
      { label: 'Renk Seçenekleri', value: 'Siyah, Kahverengi, Gri' },
      { label: 'Kullanım Alanı', value: 'Yönetici Odası, Toplantı Odası' },
      { label: 'Garanti', value: '2 Yıl Kurumsal Garanti' },
    ],
    deliveryTime: '7-10 İş Günü',
    detailedFeatures: [
      'Ücretsiz Teslimat ve Kurulum',
      '2+1 Set',
      'Premium Deri Kaplama',
      'Konforlu Tasarım',
      'Şık Görünüm',
    ],
  },
  {
    id: 11,
    name: 'Yönetici Kitaplık Seti',
    price: '17.990₺',
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=800',
    badges: ['Stokta'],
    features: ['Premium tasarım', 'Geniş raf'],
    delay: '1100ms',
    inStock: true,
    category: 'Yönetici Mobilyaları',
    description: 'Yönetici odaları için özel tasarlanmış premium kitaplık seti. Kitaplarınızı ve ödüllerinizi sergilemek için ideal.',
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=1600',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1600',
      'https://images.unsplash.com/photo-1497215842964-222b430dc094?q=80&w=1600',
    ],
    specs: [
      { label: 'Kitaplık Ölçüleri', value: '180 x 35 x 200 cm' },
      { label: 'Malzeme', value: 'Doğal Ahşap, Cam Kapılar' },
      { label: 'Renk Seçenekleri', value: 'Ceviz, Meşe, Antrasit' },
      { label: 'Kullanım Alanı', value: 'Yönetici Odası' },
      { label: 'Garanti', value: '3 Yıl Kurumsal Garanti' },
    ],
    deliveryTime: '10-14 İş Günü',
    detailedFeatures: [
      'Ücretsiz Teslimat ve Kurulum',
      'Premium Tasarım',
      'Cam Kapılı Bölmeler',
      'Geniş Raf Alanı',
      'Lüks Görünüm',
    ],
  },
  {
    id: 12,
    name: 'Yönetici TV Ünitesi',
    price: '11.990₺',
    originalPrice: '14.990₺',
    image: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?q=80&w=800',
    badges: ['Stokta'],
    features: ['Modern tasarım', 'Saklama alanı'],
    delay: '1200ms',
    inStock: true,
    category: 'Yönetici Mobilyaları',
    description: 'Yönetici odaları için şık TV ünitesi. Modern tasarımı ve saklama alanları ile ofis atmosferini zenginleştirir.',
    images: [
      'https://images.unsplash.com/photo-1497366754035-f200968a6e72?q=80&w=1600',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1600',
      'https://images.unsplash.com/photo-1497215842964-222b430dc094?q=80&w=1600',
    ],
    specs: [
      { label: 'Ünite Ölçüleri', value: '180 x 50 x 60 cm' },
      { label: 'Malzeme', value: 'Laminat, Metal Aksesuar' },
      { label: 'Renk Seçenekleri', value: 'Beyaz, Meşe, Siyah' },
      { label: 'Kullanım Alanı', value: 'Yönetici Odası, Toplantı Odası' },
      { label: 'Garanti', value: '2 Yıl Kurumsal Garanti' },
    ],
    deliveryTime: '5-7 İş Günü',
    detailedFeatures: [
      'Ücretsiz Teslimat ve Kurulum',
      'Modern Tasarım',
      'Saklama Bölmeleri',
      'Kablo Yönetim Sistemi',
      'Şık Görünüm',
    ],
  },
  {
    id: 13,
    name: 'Toplantı Odası Koltuk Seti',
    price: '21.990₺',
    originalPrice: '25.990₺',
    image: 'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?q=80&w=800',
    badges: ['Stokta'],
    features: ['8 kişilik', 'Konforlu'],
    delay: '1300ms',
    inStock: true,
    category: 'Toplantı & Ortak Alan',
    description: 'Toplantı odaları için ideal, konforlu ve şık koltuk seti. 8 kişilik kapasitesi ile büyük toplantılar için uygundur.',
    images: [
      'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?q=80&w=1600',
      'https://images.unsplash.com/photo-1497215842964-222b430dc094?q=80&w=1600',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1600',
    ],
    specs: [
      { label: 'Set İçeriği', value: '8 Koltuk' },
      { label: 'Malzeme', value: 'Kumaş Kaplama, Metal Çerçeve' },
      { label: 'Renk Seçenekleri', value: 'Gri, Mavi, Siyah' },
      { label: 'Kullanım Alanı', value: 'Toplantı Odası' },
      { label: 'Garanti', value: '2 Yıl Kurumsal Garanti' },
    ],
    deliveryTime: '7-10 İş Günü',
    detailedFeatures: [
      'Ücretsiz Teslimat ve Kurulum',
      '8 Kişilik Set',
      'Konforlu Tasarım',
      'Kumaş Kaplama',
      'Dayanıklı Yapı',
    ],
  },
  {
    id: 14,
    name: 'Oval Toplantı Masası',
    price: '16.990₺',
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=800',
    badges: ['Stokta'],
    features: ['Oval tasarım', '10 kişilik'],
    delay: '1400ms',
    inStock: true,
    category: 'Toplantı & Ortak Alan',
    description: 'Toplantı odaları için şık oval masa. 10 kişilik kapasitesi ve modern tasarımı ile dikkat çeker.',
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1600',
      'https://images.unsplash.com/photo-1497215842964-222b430dc094?q=80&w=1600',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=1600',
    ],
    specs: [
      { label: 'Masa Ölçüleri', value: '240 x 120 x 75 cm (Oval)' },
      { label: 'Malzeme', value: 'Laminat Yüzey, Metal Ayak' },
      { label: 'Renk Seçenekleri', value: 'Beyaz, Meşe, Ceviz' },
      { label: 'Kullanım Alanı', value: 'Toplantı Odası' },
      { label: 'Garanti', value: '2 Yıl Kurumsal Garanti' },
    ],
    deliveryTime: '7-10 İş Günü',
    detailedFeatures: [
      'Ücretsiz Teslimat ve Kurulum',
      'Oval Tasarım',
      '10 Kişilik Kapasite',
      'Kablo Yönetim Sistemi',
      'Modern Görünüm',
    ],
  },
  {
    id: 15,
    name: 'Bekleme Alanı Koltuk Seti',
    price: '13.990₺',
    originalPrice: '16.990₺',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=800',
    badges: ['Stokta'],
    features: ['6 kişilik', 'Bekleme alanı'],
    delay: '1500ms',
    inStock: true,
    category: 'Toplantı & Ortak Alan',
    description: 'Bekleme alanları ve resepsiyon için konforlu koltuk seti. Modern tasarımı ile misafirlerinize rahat bir bekleme deneyimi sunar.',
    images: [
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=1600',
      'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?q=80&w=1600',
      'https://images.unsplash.com/photo-1497215842964-222b430dc094?q=80&w=1600',
    ],
    specs: [
      { label: 'Set İçeriği', value: '6 Koltuk' },
      { label: 'Malzeme', value: 'Kumaş Kaplama, Metal Çerçeve' },
      { label: 'Renk Seçenekleri', value: 'Gri, Mavi, Kırmızı' },
      { label: 'Kullanım Alanı', value: 'Bekleme Alanı, Resepsiyon' },
      { label: 'Garanti', value: '2 Yıl Kurumsal Garanti' },
    ],
    deliveryTime: '5-7 İş Günü',
    detailedFeatures: [
      'Ücretsiz Teslimat ve Kurulum',
      '6 Kişilik Set',
      'Konforlu Tasarım',
      'Modern Görünüm',
      'Dayanıklı Yapı',
    ],
  },
  {
    id: 16,
    name: 'Toplantı Odası Projeksiyon Ünitesi',
    price: '9.990₺',
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=800',
    badges: ['Stokta'],
    features: ['Projeksiyon için', 'Ayarlanabilir'],
    delay: '1600ms',
    inStock: true,
    category: 'Toplantı & Ortak Alan',
    description: 'Toplantı odaları için projeksiyon cihazı ünitesi. Ayarlanabilir yüksekliği ile her türlü sunum için uygundur.',
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=1600',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1600',
      'https://images.unsplash.com/photo-1497215842964-222b430dc094?q=80&w=1600',
    ],
    specs: [
      { label: 'Ünite Ölçüleri', value: '60 x 60 x 120-180 cm (Ayarlanabilir)' },
      { label: 'Malzeme', value: 'Metal, Plastik Aksesuar' },
      { label: 'Renk Seçenekleri', value: 'Siyah, Beyaz' },
      { label: 'Kullanım Alanı', value: 'Toplantı Odası, Konferans Salonu' },
      { label: 'Garanti', value: '1 Yıl Kurumsal Garanti' },
    ],
    deliveryTime: '3-5 İş Günü',
    detailedFeatures: [
      'Ücretsiz Teslimat',
      'Ayarlanabilir Yükseklik',
      'Hareketli Tekerlekler',
      'Projeksiyon Uyumlu',
      'Pratik Tasarım',
    ],
  },
  {
    id: 17,
    name: 'Arşiv Dolabı',
    price: '12.990₺',
    originalPrice: '15.990₺',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=800',
    badges: ['Stokta'],
    features: ['Geniş kapasite', 'Dosya sistemi'],
    delay: '1700ms',
    inStock: true,
    category: 'Depolama',
    description: 'Ofisler için geniş kapasiteli arşiv dolabı. Dosya ve evrak organizasyonu için ideal depolama çözümü.',
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=1600',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1600',
      'https://images.unsplash.com/photo-1497215842964-222b430dc094?q=80&w=1600',
    ],
    specs: [
      { label: 'Dolap Ölçüleri', value: '100 x 50 x 200 cm' },
      { label: 'Malzeme', value: 'Metal, Laminat Kapı' },
      { label: 'Renk Seçenekleri', value: 'Gri, Beyaz, Siyah' },
      { label: 'Kullanım Alanı', value: 'Arşiv Odası, Depo' },
      { label: 'Garanti', value: '2 Yıl Kurumsal Garanti' },
    ],
    deliveryTime: '5-7 İş Günü',
    detailedFeatures: [
      'Ücretsiz Teslimat ve Kurulum',
      'Geniş Depolama Kapasitesi',
      'Dosya Sistemi',
      'Kilitli Bölmeler',
      'Dayanıklı Yapı',
    ],
  },
  {
    id: 18,
    name: 'Mobil Depolama Ünitesi',
    price: '8.990₺',
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?q=80&w=800',
    badges: ['Stokta'],
    features: ['Tekerlekli', 'Pratik'],
    delay: '1800ms',
    inStock: true,
    category: 'Depolama',
    description: 'Ofisler için pratik mobil depolama ünitesi. Tekerlekli tasarımı ile istediğiniz yere kolayca taşıyabilirsiniz.',
    images: [
      'https://images.unsplash.com/photo-1497366754035-f200968a6e72?q=80&w=1600',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=1600',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1600',
    ],
    specs: [
      { label: 'Ünite Ölçüleri', value: '80 x 40 x 90 cm' },
      { label: 'Malzeme', value: 'Metal, Plastik Tekerlek' },
      { label: 'Renk Seçenekleri', value: 'Gri, Beyaz, Siyah' },
      { label: 'Kullanım Alanı', value: 'Ofis, Depo' },
      { label: 'Garanti', value: '1 Yıl Kurumsal Garanti' },
    ],
    deliveryTime: '3-5 İş Günü',
    detailedFeatures: [
      'Ücretsiz Teslimat',
      'Tekerlekli Tasarım',
      'Pratik Kullanım',
      'Geniş Depolama',
      'Hareketli',
    ],
  },
  {
    id: 19,
    name: 'Dosya Dolabı Seti',
    price: '10.990₺',
    originalPrice: '13.990₺',
    image: 'https://images.unsplash.com/photo-1497215842964-222b430dc094?q=80&w=800',
    badges: ['Stokta'],
    features: ['4 çekmeceli', 'Dosya sistemi'],
    delay: '1900ms',
    inStock: true,
    category: 'Depolama',
    description: 'Ofisler için pratik dosya dolabı seti. 4 çekmeceli tasarımı ile dosya organizasyonu için ideal.',
    images: [
      'https://images.unsplash.com/photo-1497215842964-222b430dc094?q=80&w=1600',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=1600',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1600',
    ],
    specs: [
      { label: 'Dolap Ölçüleri', value: '90 x 45 x 120 cm' },
      { label: 'Malzeme', value: 'Metal, Plastik Çekmece' },
      { label: 'Renk Seçenekleri', value: 'Gri, Beyaz, Siyah' },
      { label: 'Kullanım Alanı', value: 'Ofis, Arşiv' },
      { label: 'Garanti', value: '2 Yıl Kurumsal Garanti' },
    ],
    deliveryTime: '5-7 İş Günü',
    detailedFeatures: [
      'Ücretsiz Teslimat ve Kurulum',
      '4 Çekmeceli',
      'Dosya Sistemi',
      'Kilitli Çekmeceler',
      'Pratik Tasarım',
    ],
  },
  {
    id: 20,
    name: 'Raf Sistemi',
    price: '7.990₺',
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=800',
    badges: ['Stokta'],
    features: ['Modüler', 'Genişletilebilir'],
    delay: '2000ms',
    inStock: true,
    category: 'Depolama',
    description: 'Ofisler için modüler raf sistemi. Genişletilebilir yapısı ile ihtiyacınıza göre özelleştirilebilir.',
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1600',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=1600',
      'https://images.unsplash.com/photo-1497215842964-222b430dc094?q=80&w=1600',
    ],
    specs: [
      { label: 'Raf Ölçüleri', value: '120 x 40 x 180 cm' },
      { label: 'Malzeme', value: 'Metal, Laminat Raf' },
      { label: 'Renk Seçenekleri', value: 'Gri, Beyaz, Siyah' },
      { label: 'Kullanım Alanı', value: 'Depo, Arşiv' },
      { label: 'Garanti', value: '2 Yıl Kurumsal Garanti' },
    ],
    deliveryTime: '5-7 İş Günü',
    detailedFeatures: [
      'Ücretsiz Teslimat ve Kurulum',
      'Modüler Tasarım',
      'Genişletilebilir',
      'Ayarlanabilir Raf Yüksekliği',
      'Dayanıklı Yapı',
    ],
  },
  {
    id: 21,
    name: 'Kilitli Depolama Dolabı',
    price: '14.990₺',
    originalPrice: '17.990₺',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=800',
    badges: ['Stokta'],
    features: ['Kilitli', 'Güvenli'],
    delay: '2100ms',
    inStock: true,
    category: 'Depolama',
    description: 'Ofisler için güvenli kilitli depolama dolabı. Önemli evraklar ve değerli eşyalar için ideal güvenlik çözümü.',
    images: [
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=1600',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=1600',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1600',
    ],
    specs: [
      { label: 'Dolap Ölçüleri', value: '120 x 50 x 180 cm' },
      { label: 'Malzeme', value: 'Metal, Kilitli Kapı' },
      { label: 'Renk Seçenekleri', value: 'Gri, Beyaz, Siyah' },
      { label: 'Kullanım Alanı', value: 'Ofis, Güvenli Depo' },
      { label: 'Garanti', value: '2 Yıl Kurumsal Garanti' },
    ],
    deliveryTime: '7-10 İş Günü',
    detailedFeatures: [
      'Ücretsiz Teslimat ve Kurulum',
      'Kilitli Sistem',
      'Güvenli Depolama',
      'Geniş İç Alan',
      'Dayanıklı Yapı',
    ],
  },
  {
    id: 22,
    name: 'Özel Proje Ofis Seti',
    price: 'Teklif Al',
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?q=80&w=800',
    badges: ['Özel Üretim'],
    features: ['Özel tasarım', 'Proje bazlı'],
    delay: '2200ms',
    inStock: false,
    category: 'Proje / Özel Üretim',
    description: 'Kurumsal projeler için özel tasarlanmış ofis seti. İhtiyacınıza göre özelleştirilebilir tasarım ve üretim hizmeti.',
    images: [
      'https://images.unsplash.com/photo-1497366754035-f200968a6e72?q=80&w=1600',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1600',
      'https://images.unsplash.com/photo-1497215842964-222b430dc094?q=80&w=1600',
    ],
    specs: [
      { label: 'Ölçüler', value: 'Projeye Özel' },
      { label: 'Malzeme', value: 'Müşteri Tercihine Göre' },
      { label: 'Renk Seçenekleri', value: 'Müşteri Tercihine Göre' },
      { label: 'Kullanım Alanı', value: 'Projeye Özel' },
      { label: 'Garanti', value: 'Projeye Özel' },
    ],
    deliveryTime: 'Projeye Özel',
    detailedFeatures: [
      'Özel Tasarım',
      'Proje Bazlı Üretim',
      'İç Mimari Danışmanlık',
      'Özel Ölçü',
      'Premium Malzeme Seçenekleri',
    ],
  },
  {
    id: 23,
    name: 'Kurumsal Proje Mobilya Seti',
    price: 'Teklif Al',
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=800',
    badges: ['Özel Üretim'],
    features: ['Toplu alım', 'Proje bazlı'],
    delay: '2300ms',
    inStock: false,
    category: 'Proje / Özel Üretim',
    description: 'Büyük kurumsal projeler için özel mobilya seti. Toplu alımlarda özel fiyatlandırma ve tasarım hizmeti.',
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1600',
      'https://images.unsplash.com/photo-1497215842964-222b430dc094?q=80&w=1600',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=1600',
    ],
    specs: [
      { label: 'Ölçüler', value: 'Projeye Özel' },
      { label: 'Malzeme', value: 'Müşteri Tercihine Göre' },
      { label: 'Renk Seçenekleri', value: 'Müşteri Tercihine Göre' },
      { label: 'Kullanım Alanı', value: 'Kurumsal Proje' },
      { label: 'Garanti', value: 'Projeye Özel' },
    ],
    deliveryTime: 'Projeye Özel',
    detailedFeatures: [
      'Toplu Alım İndirimi',
      'Özel Tasarım',
      'Proje Yönetimi',
      'İç Mimari Danışmanlık',
      'Kurulum Hizmeti',
    ],
  },
  {
    id: 24,
    name: 'Özel Ölçü Masa Üretimi',
    price: 'Teklif Al',
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1497215842964-222b430dc094?q=80&w=800',
    badges: ['Özel Üretim'],
    features: ['Özel ölçü', 'Kişiye özel'],
    delay: '2400ms',
    inStock: false,
    category: 'Proje / Özel Üretim',
    description: 'İhtiyacınıza özel ölçülerde masa üretimi. Her türlü boyut ve tasarım seçeneği ile hayalinizdeki masayı üretiyoruz.',
    images: [
      'https://images.unsplash.com/photo-1497215842964-222b430dc094?q=80&w=1600',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1600',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=1600',
    ],
    specs: [
      { label: 'Ölçüler', value: 'Müşteri Ölçülerine Göre' },
      { label: 'Malzeme', value: 'Müşteri Tercihine Göre' },
      { label: 'Renk Seçenekleri', value: 'Müşteri Tercihine Göre' },
      { label: 'Kullanım Alanı', value: 'Müşteri İhtiyacına Göre' },
      { label: 'Garanti', value: '2 Yıl Kurumsal Garanti' },
    ],
    deliveryTime: '14-21 İş Günü',
    detailedFeatures: [
      'Özel Ölçü',
      'Kişiye Özel Tasarım',
      'Malzeme Seçimi',
      'Renk Seçimi',
      'Ücretsiz Kurulum',
    ],
  },
  {
    id: 25,
    name: 'İç Mimari Proje Danışmanlığı',
    price: 'Teklif Al',
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?q=80&w=800',
    badges: ['Danışmanlık'],
    features: ['İç mimari', 'Proje yönetimi'],
    delay: '2500ms',
    inStock: false,
    category: 'Proje / Özel Üretim',
    description: 'Kurumsal projeleriniz için profesyonel iç mimari danışmanlık hizmeti. Ofis tasarımından mobilya seçimine kadar tüm süreçte yanınızdayız.',
    images: [
      'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?q=80&w=1600',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1600',
      'https://images.unsplash.com/photo-1497215842964-222b430dc094?q=80&w=1600',
    ],
    specs: [
      { label: 'Hizmet Kapsamı', value: 'İç Mimari Tasarım' },
      { label: 'Süre', value: 'Projeye Özel' },
      { label: 'Danışmanlık', value: 'Profesyonel Ekip' },
      { label: 'Kullanım Alanı', value: 'Kurumsal Projeler' },
      { label: 'Garanti', value: 'Proje Bazlı' },
    ],
    deliveryTime: 'Projeye Özel',
    detailedFeatures: [
      'İç Mimari Tasarım',
      '3D Görselleştirme',
      'Mobilya Seçimi',
      'Proje Yönetimi',
      'Kurulum Takibi',
    ],
  },
  {
    id: 26,
    name: 'Kurumsal Toplu Alım Paketi',
    price: 'Teklif Al',
    originalPrice: null,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=800',
    badges: ['Toplu Alım'],
    features: ['Toplu alım', 'Özel fiyat'],
    delay: '2600ms',
    inStock: false,
    category: 'Proje / Özel Üretim',
    description: 'Büyük kurumsal alımlar için özel paket fiyatlandırması. Toplu alımlarda özel indirimler ve kurulum hizmeti.',
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=1600',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1600',
      'https://images.unsplash.com/photo-1497215842964-222b430dc094?q=80&w=1600',
    ],
    specs: [
      { label: 'Paket İçeriği', value: 'Müşteri İhtiyacına Göre' },
      { label: 'Adet', value: 'Toplu Alım' },
      { label: 'Fiyatlandırma', value: 'Özel Teklif' },
      { label: 'Kullanım Alanı', value: 'Kurumsal Projeler' },
      { label: 'Garanti', value: 'Projeye Özel' },
    ],
    deliveryTime: 'Projeye Özel',
    detailedFeatures: [
      'Toplu Alım İndirimi',
      'Özel Fiyatlandırma',
      'Proje Yönetimi',
      'Toplu Kurulum',
      'Öncelikli Destek',
    ],
  },
];

export const COMPANY_STATS = {
  years: '25+',
  branches: '8',
  cities: '6',
  projects: '1000+',
};

export const FOOTER_LINKS = {
  shop: [
    { href: '/category/1', label: 'Ofis Mobilyaları' },
    { href: '/category/2', label: 'Yönetici Mobilyaları' },
    { href: '/category/3', label: 'Toplantı & Ortak Alan' },
    { href: '/category/4', label: 'Depolama Sistemleri' },
    { href: '/category/5', label: 'Proje / Özel Üretim' },
  ],
  company: [
    { href: '/about', label: 'Hakkımızda' },
    { href: '/projects', label: 'Projelerimiz' },
    { href: '/references', label: 'Referanslar' },
    { href: '/career', label: 'Kariyer' },
  ],
  support: [
    { href: '/support', label: 'Satış Sonrası Destek' },
    { href: '/warranty', label: 'Garanti & Bakım' },
    { href: '/delivery', label: 'Teslimat Bilgileri' },
    { href: '/track-order', label: 'Sipariş Takibi' },
  ],
};

export const CONTACT_INFO = {
  address: 'Mobilya Caddesi No:142,\nTasarım Mahallesi, İstanbul',
  phone: '+90 (555) 123 45 67',
  email: 'satis@wmb.com',
  workingHours: 'Pazartesi - Cumartesi: 09:00 - 18:00',
};
